##    Import necessary packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(texreg)
# Fastest package for adding cluster-robust standard errors:
# https://www.r-bloggers.com/2021/05/clustered-standard-errors-with-r/#google_vignette 
#library(estimatr)
library(fixest)
library(tidyverse)
library(readxl)
library(table.express)
library(data.table)
#library(progressr)

options(digits = 1)
#handlers(global = TRUE) #  For progress bars
```

##    Setup
Directories and filenames that change with machine
```{r directory, include=FALSE}
#directory = "/nfs/turbo/lsa-areynoso"
directory = "/Volumes/lsa-areynoso"

geos = c("cbsa","state")
#geos = c("state")
avgs = c(7,5,3,1)
#avgs = c(7,5)
#norm = c("","_ptile")
norm = c("","_ptile")
stage = c("_shock","_growth")
shock_lbl = c("1-Year Shock",
              "3-Year Average",
              "5-Year Average",
              "7-Year Average")
# Number of bins is flexible
num_bins = c(5,10)
universes = c("stay","leave_hs","leave_col")
```

##    Create Universal Label

```{r label}

# Function to generate variable labels for multiple prefixes
generate_labels <- function(var_prefixes, avgs, inst_groups) {
  labels_list <- lapply(var_prefixes, function(var_prefix) {
    labels <- paste0(var_prefix, "_", avgs, ":")
    do.call(paste0, expand.grid(labels, inst_groups))
  })
  unlist(labels_list)  # Flatten the list into a single vector
}

controls = c("in_stateIn-State",
             "non_traditionalTraditional",
             "transferTransfer")
control_lbl = c("College In State",
                "BA by Age 24",
                "Transfer Student")
inst_groups = c("inst_groupPrivate, For-Profit",
                "inst_groupPrivate, Non-Profit",
                "inst_groupRPU")
                #"inst_groupRPU, Less Selective",
                #"inst_groupRPU, More Selective")

# Create Universal Labels
output_instate = paste0(inst_groups, ":in_stateIn-State")
output_dist = paste0("dist", c("[0,50]", "(50,100]", "(100,150]", "(150,200]", 
                                "(200,250]", "(250,500]", "(500,1e+03]", "(1e+03,1e+04]"))

# Crete labor demand shock variables
hs_vars = paste0("hs",do.call(paste0, expand.grid(stage, norm, stringsAsFactors = FALSE)))
col_vars = paste0("col",do.call(paste0, expand.grid(stage, norm, stringsAsFactors = FALSE)))

# Generate labels for all variable types
hs_output_vars = generate_labels(hs_vars, avgs, inst_groups)
col_output_vars = generate_labels(col_vars, avgs, inst_groups)

# Create labels for hs_shock * dist (using the original prefix)
output_distance = paste0(rep(paste0(rep(hs_vars,each = length(avgs)),"_",avgs,":"),each = length(output_dist)),output_dist) 

# Combine all interaction labels
interactions = c(output_instate, hs_output_vars, col_output_vars, output_distance)

# Remove variable names through flexible regex
basic_pattern = "[^0-9]*[0-9]+"
hs_pattern <- paste0("hs",basic_pattern)
col_pattern <- paste0("col",basic_pattern)


# Create clean labels for final table
interactions_lbl = c(paste0(str_replace_all(inst_groups, "inst_group", ""), " $times$ In-State"),
                     paste0(str_replace_all(hs_output_vars, paste0(hs_pattern,"(:inst_group)?"), ""), " $times$ HS LD Shock"),
                     paste0(str_replace_all(col_output_vars, paste0(col_pattern,"(:inst_group)?"), ""), " $times$ College LD Shock"),
                     paste0(str_replace_all(output_distance, paste0(hs_pattern,"(:dist)?"), ""), " $times$ HS LD Shock"))

# Bind regression outputs with cleaned names
label = data.frame(output_names = c(do.call(paste, expand.grid(hs_vars, avgs, stringsAsFactors = FALSE, sep = "_")),
                                    do.call(paste, expand.grid(col_vars, avgs, stringsAsFactors = FALSE, sep = "_")),
                                    inst_groups,
                                    output_dist,
                                    interactions,
                                    controls),
                   label_names = c(rep(times = length(avgs) * length(hs_vars),"HS LD Shock"),
                                   rep(times = length(avgs) * length(col_vars),"College LD Shock"),
                                   str_replace_all(inst_groups,"inst_group",""),
                                   str_replace_all(output_dist,"dist",""),
                                   interactions_lbl,
                                   control_lbl))

nestedlist <- split(label$label_names, factor(label$output_names, 
                                               levels = unique(label$output_names)))

```

##    Semi-Elasticity Regressions

```{r}

models <- list()
group_semi_elasticities <- data.frame()
# Prepare data to collect coefficients
coef_data <- data.frame()
#norm = c("")


for(h in geos) 
{
  for(u in universes)
  {
    print(paste0("Universe: ",u))
    data <- if(h == "cbsa") regression_cbsa else regression_state
    # Filter data based on the universe condition
    if(u == "stay") {
      data <- data[data$hs_cbsa_code == data$col_cbsa_code, ]
    } else {
      data <- data[data$hs_cbsa_code != data$col_cbsa_code, ]
    }
    data <- data[!col_end %in% c(2019:2023)]
    for(a in avgs) 
    {
      for(n in norm)
      {
        for(s in stage) 
        {
          hs_var <- paste0("hs", s, n, "_", a)
          col_var <- paste0("col", s, n, "_", a)
          current_stay <- paste0("same_", h, "_hs_10 ~ ",hs_var)
          current_hs <- paste0("same_", h, "_hs_10 ~ ", paste(hs_var, col_var, sep=" + "))
          current_col <- paste0("same_", h, "_col_10 ~ ", paste(hs_var, col_var, sep=" + "))

          if(u == "stay") 
          {
            formula <- c(
              current_stay,
              paste0(current_stay, " + inst_group + in_state + (inst_group * in_state)"),
              paste0(current_stay, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin"),
              paste0(current_stay, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin + col_end"),
              paste0(current_stay, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin + col_end + hs_state")
            ) 
          }
          if(u == "leave_hs") 
          {
            formula <- c(
              current_hs,
              paste0(current_hs, " + inst_group + in_state + (inst_group * in_state)"),
              paste0(current_hs, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin"),
              paste0(current_hs, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin + col_end"),
              paste0(current_hs, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin + col_end + hs_state")
            ) 
          }
          if(u == "leave_col") 
          {
            formula <- c(
              current_col,
              paste0(current_col, " + inst_group + in_state + (inst_group * in_state)"),
              paste0(current_col, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin"),
              paste0(current_col, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin + col_end"),
              paste0(current_col, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + prestige_bin + col_end + hs_state")
            ) 
          }
          
          # Add progress bar
          #progressr::with_progress({
          #  p <- progressr::progressor(steps = length(formula))
          
          for (f in 1:length(formula)) 
          {
            print(paste0("Solving: Specification ",f,s))
            form <- formula[f]
            # Clustered regression
            model <- fixest::feols(
              as.formula(form),
              data = data,
              cluster = ~hs_cbsa_code
            )
            
            #p()
            
            models[[paste0(h, s, n, "_avg_", a, "_", f, "_", u)]] <- model
            print(paste0("Solved: Specification ",f,s))
            if(u == "stay") 
            {
              # Extract coefficients and confidence intervals
              model_key <- paste0(h, stage[1], norm[1], "_avg_", a, "_", f, "_", u)
              coef_data <- coef_data %>%
                bind_rows(
                  data.frame(
                    hs_var = hs_var,
                    col_var = hs_var,
                    universe = u,
                    geo = h,
                    avg = a,
                    model = f,
                    hs_coef = coef(model)[hs_var],
                    hs_conf_low = confint(model)[hs_var, 1],
                    hs_conf_high = confint(model)[hs_var, 2],
                    col_coef = coef(model)[hs_var],
                    col_conf_low = confint(model)[hs_var, 1],
                    col_conf_high = confint(model)[hs_var, 2]
                  )
                )
              hs_coef = coef(model)[hs_var]
              col_coef = coef(model)[hs_var]
            } else {# Extract coefficients and confidence intervals
              model_key <- paste0(h, stage[1], norm[1], "_avg_", a, "_", f, "_", u)
              coef_data <- coef_data %>%
                bind_rows(
                  data.frame(
                    hs_var = hs_var,
                    col_var = col_var,
                    universe = u,
                    geo = h,
                    avg = a,
                    model = f,
                    hs_coef = coef(model)[hs_var],
                    hs_conf_low = confint(model)[hs_var, 1],
                    hs_conf_high = confint(model)[hs_var, 2],
                    col_coef = coef(model)[col_var],
                    col_conf_low = confint(model)[col_var, 1],
                    col_conf_high = confint(model)[col_var, 2]
                  )
                )
                hs_coef = coef(model)[hs_var]
                col_coef = coef(model)[col_var]
            }
          } # Closes for loop that evaluates formulae
          #})   For progress bar
          print(paste("Finished with",u,s,sep=" "))
          for(inst in unique(data$inst_group))
          {
            for(in_state in unique(data$in_state))
            {
              
              # Determine coefficients for current group
              inst_coef <- ifelse(inst == "PF", 0, coef(model)[paste0("inst_group", inst)])
              in_state_coef <- ifelse(in_state == "Out-of-State", 0, coef(model)[paste0("in_state", in_state)])
              interaction_coef <- ifelse(
                inst == "PF" || in_state == "Out-of-State",
                0,
                coef(model)[paste0("inst_group", inst, ":in_state", in_state)]
              )
    
              # Calculate semi-elasticity for high school labor demand (hs_var)
              hs_group_semi <- (hs_coef + inst_coef + in_state_coef + interaction_coef)
          
              # Calculate semi-elasticity for college labor demand (col_var)
              col_group_semi <- (col_coef + inst_coef + in_state_coef + interaction_coef)
          
              # Store results in dataframe
              group_semi_elasticities <- group_semi_elasticities %>%
                bind_rows(data.frame(
                    geo = h,
                    avg = a,
                    norm = n,
                    stage = s,
                    universe = u,
                    inst_group = inst,
                    in_state = in_state,
                    hs_semi_elasticity = hs_group_semi,
                    col_semi_elasticity = col_group_semi
                    ))
              }
            }
          
          # Define control inclusion for each model
          controls <- list(
            "Undergraduate Major FE" = c("No", "No", "Yes", "Yes", "Yes", "No", "No", "Yes", "Yes", "Yes"),
            "Transfer and Non-Traditional FE" = c("No", "No", "Yes", "Yes", "Yes", "No", "No", "Yes", "Yes", "Yes"),
            "Occupational Group FE" = c("No", "No", "Yes", "Yes", "Yes", "No", "No", "Yes", "Yes", "Yes"),
            "Occupational Prestige Bin FE" = c("No", "No", "Yes", "Yes", "Yes", "No", "No", "Yes", "Yes", "Yes"),
            "Year of College Graduation FE" = c("No", "No", "No", "Yes", "Yes", "No", "No", "No", "Yes", "Yes"),
            "High School State FE" = c("No", "No", "No", "No", "Yes", "No", "No", "No", "No", "Yes")
          )
        }
        tsls_models <- list(
            models[[paste0(h, stage[1], n, "_avg_", a, "_1", "_", u)]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_2", "_", u)]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_3", "_", u)]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_4", "_", u)]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_5", "_", u)]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_1", "_", u)]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_2", "_", u)]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_3", "_", u)]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_4", "_", u)]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_5", "_", u)]])
        
        # Combine with the label
        #my_values <- sapply(tsls_models, function(model) 
        #{
        #  if (!is.null(model)) 
        #  {
        #    fit <- fixest::fitstat(model, type = "my")
         #   if (!is.null(fit[["my"]])) 
         #   {
         #     return(round(fit[["my"]],3))
        #    }
        #  }
       #   return(NA)  # Return NA if missing
       # })
        #my <- c("Mean Return Shr.", my_values)
        
        
        # Output LaTeX table
        texreg(tsls_models,
          custom.model.names = rep(paste0("(", 1:5, ")"), 2),
          label = paste0("table:opt_", h, n, "_", a),
          include.ci = FALSE,
          caption = paste0(
           "Probability of returning to high school ", h," within 10 years of college graduation. ",
          captions[[paste0("leave_hs_",a)]]),
          center = FALSE,
          digits = 3,
          custom.gof.rows = controls,
          custom.coef.map = nestedlist,
          file = paste0(directory, "/Outputs/Tables/opt_", h, n, "_", a, "_", u,"_final.tex"),
          append = TRUE
        )
      }
    }
  }
}

write.csv(group_semi_elasticities,file.path(directory,"Data/06","group_semi_elasticities.csv"))
write.csv(coef_data,file.path(directory,"Data/06","coef_data_semi.csv"))
  
cbsa_shock_ptile <- fread(file.path(directory,"Data/04","cbsa_shock.csv")) %>%
  table.express::select(year,cbsa_code,shock_avg_7,ptile_shock_avg_7)
cbsa_shock_ptile[,year := factor(year)]

# Extract semi-elasticities for relevant return measurement
# First, return to high school labor market
semi_cbsa <- group_semi_elasticities %>%
  table.express::filter(geo == "cbsa" & avg == 7 & norm != "_ptile" & stage == "_shock") %>%
  table.express::select(inst_group,in_state,hs_semi_elasticity)
# Next, return to high school state
semi_state <- group_semi_elasticities %>%
  table.express::filter(geo == "state" & avg == 7 & norm != "_ptile" & stage == "_shock") %>%
  table.express::select(inst_group,in_state,hs_semi_elasticity)

# Compute predictions for labor market returns across entire sample
predictions_cbsa <- regression[,.N,by=.(col_end,inst_group,in_state,same_cbsa_hs,ever_leave_cbsa_hs)] %>%
  dcast(col_end + inst_group + in_state ~ same_cbsa_hs + ever_leave_cbsa_hs,
         value.var = "N", fill = 0)
setnames(predictions_cbsa, old = c("0_0", "0_1", "1_0", "1_1"), 
  new = c("weird", "pred_leavers", "pred_stayers", "pred_returners"))
predictions_cbsa[,pred_shr_returners_base := pred_returners/(pred_returners+pred_leavers)]
predictions_cbsa <- predictions_cbsa[, .(col_end,inst_group,in_state,pred_shr_returners_base)]
# Compute predictions for state returns across entire sample
predictions_state <- regression[,.N,by=.(col_end,inst_group,in_state,same_state_hs,ever_leave_state_hs)] %>%
  dcast(col_end + inst_group + in_state ~ same_state_hs + ever_leave_state_hs,
        value.var = "N",fill = 0)
setnames(predictions_state, old = c("0_0", "0_1", "1_0", "1_1"),
         skip_absent = TRUE,
  new = c("weird", "pred_leavers", "pred_stayers", "pred_returners"))
predictions_state[,pred_shr_returners_base := pred_returners/(pred_returners+pred_leavers)]
predictions_state <- predictions_state[, .(col_end,inst_group,in_state,pred_shr_returners_base)]

# Compute labor market x year of college graduation return rates, to compare against predictions
empir_cbsa <- regression[,.N,by=.(col_end,hs_cbsa,inst_group,in_state,same_cbsa_hs,ever_leave_cbsa_hs)] %>%
  dcast( hs_cbsa + col_end + inst_group + in_state ~ same_cbsa_hs + ever_leave_cbsa_hs,
         value.var = "N", fill = 0) %>%
  merge(cbsa_shock_ptile, by.x = c("hs_cbsa","col_end"), by.y = c("cbsa_code","year"), all.x=TRUE) %>%
  merge(predictions_cbsa, by = c("col_end","inst_group","in_state"),all.x=TRUE) %>% #  Watch whether Cartesian fucks anything up
  merge(semi_cbsa, by = c("inst_group","in_state"),all.x=TRUE,allow.cartesian = TRUE)
# Renaming columns based on conditions
setnames(empir_cbsa, old = c("0_0", "0_1", "1_0", "1_1"),  # Original column names from dcast
  new = c("weird", "leavers", "stayers", "returners"))
empir_cbsa[,total_non_stayers := returners+leavers]
empir_cbsa[,shr_returners := returners/total_non_stayers]
empir_cbsa[,pred_shr_returners := pred_shr_returners_base + (shock_avg_7 * hs_semi_elasticity)]
# Next aggregate upward, taking weighted average of predictions and actual return rates
# for different combinations of in_state and inst_group
diff_cbsa <- empir_cbsa[, .(shr_returners = weighted.mean(shr_returners,w=total_non_stayers,na.rm=TRUE),
                             pred_shr_returners = weighted.mean(pred_shr_returners,w=total_non_stayers,na.rm=TRUE),
                             difference = shr_returners - pred_shr_returners), by = .(col_end,hs_cbsa)]
# Between 2000 and 2022, by how many percentage points did the local labor market's return
# rate exceed the prediction, controlling for year and where natives attended college
diff_cbsa <- diff_cbsa[, .(shr_returners_cbsa = mean(shr_returners,na.rm=TRUE),
                           pred_shr_returners_cbsa = mean(pred_shr_returners,na.rm=TRUE),
                           difference_cbsa = mean(difference, na.rm=TRUE)),by=.(hs_cbsa)]

# Compute state x year of college graduation return rates, to compare against predictions
empir_state <- regression[,.N,by=.(col_end,hs_cbsa,inst_group,in_state,same_state_hs,ever_leave_state_hs)] %>%
  dcast( hs_cbsa + col_end + inst_group + in_state ~ same_state_hs + ever_leave_state_hs,
         value.var = "N", fill = 0) %>%
  merge(cbsa_shock_ptile, by.x = c("hs_cbsa","col_end"), by.y = c("cbsa_code","year"), all.x=TRUE) %>%
  merge(predictions_state, by = c("col_end","inst_group","in_state"),all.x=TRUE) %>%
  merge(semi_state, by = c("inst_group","in_state"),all.x=TRUE,allow.cartesian = TRUE)
# Renaming columns based on conditions
setnames(empir_state, old = c("0_0", "0_1", "1_0", "1_1"),  # Original column names from dcast
  new = c("weird", "leavers", "stayers", "returners"),
  skip_absent = TRUE)
empir_state[,total_non_stayers := returners+leavers]
empir_state[,shr_returners := returners/total_non_stayers]
empir_state[,pred_shr_returners := pred_shr_returners_base + (shock_avg_7 * hs_semi_elasticity)]
# Next aggregate upward, taking weighted average of predictions and actual return rates
# for different combinations of in_state and inst_group
diff_state <- empir_state[, .(shr_returners = weighted.mean(shr_returners,w=total_non_stayers,na.rm=TRUE),
                             pred_shr_returners = weighted.mean(pred_shr_returners,w=total_non_stayers,na.rm=TRUE),
                             difference= shr_returners - pred_shr_returners), by = .(col_end,hs_cbsa)]
# Between 2000 and 2022, by how many percentage points did the local labor market's return
# rate exceed the prediction, controlling for year and where natives attended college
diff_state <- diff_state[, .(shr_returners_state = mean(shr_returners,na.rm=TRUE),
                           pred_shr_returners_state = mean(pred_shr_returners,na.rm=TRUE),
                           difference_state = mean(difference, na.rm=TRUE)),by=.(hs_cbsa)]

# Merge labor market and state-level analyses into single object for export
differences <- merge(diff_state,diff_cbsa,by=c("hs_cbsa"))

# Export merged file
write.csv(differences,file.path(directory,"Data/06","local_differences.csv"))

```

##      Second Stage

```{r second-stage}

models <- list()
years <- 2000:2021
# Prepare data to collect coefficients
coef_data <- data.frame()

for(yr in years)
{
  for(h in geos) {
    data <- if(h == "cbsa") regression_cbsa else regression_state
    data <- data[col_end == yr]
    for(a in avgs) {
      # Retrieve relevant statistics for the current average type
      hs_f_stat <- hs_stats[[as.character(a)]]$f_stat
      hs_r_squared <- hs_stats[[as.character(a)]]$r_squared
      col_f_stat <- col_stats[[as.character(a)]]$f_stat
      col_r_squared <- col_stats[[as.character(a)]]$r_squared
      for(n in norm)
      {
        for(s in stage) 
        {
          hs_var <- paste0("hs", s, n, "_", a)
          col_var <- paste0("col", s, n, "_", a)
          current <- paste0("same_", h, "_hs ~ ", paste(hs_var, col_var, sep=" + "))
          
          formula <- c(
            current,
            paste0(current, " + inst_group + in_state + (inst_group * in_state)"),
            paste0(current, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3"),
            paste0(current, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + col_end"),
            paste0(current, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + col_end + hs_state")
          )
          
          }
          
          
        
          # Define control inclusion for each model
          controls <- list(
            "Undergraduate Major FE" = c("No", "No", "Yes", "Yes", "Yes", "No", "No", "Yes", "Yes", "Yes"),
            "Transfer and Non-Traditional FE" = c("No", "No", "Yes", "Yes", "Yes", "No", "No", "Yes", "Yes", "Yes"),
            "Occupational Group FE" = c("No", "No", "Yes", "Yes", "Yes", "No", "No", "Yes", "Yes", "Yes"),
            "Year of College Graduation FE" = c("No", "No", "No", "Yes", "Yes", "No", "No", "No", "Yes", "Yes"),
            "High School State FE" = c("No", "No", "No", "No", "Yes", "No", "No", "No", "No", "Yes")
          )
        }
        texreg(
          list(
            models[[paste0(h, stage[1], n, "_avg_", a, "_1")]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_2")]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_3")]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_4")]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_5")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_1")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_2")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_3")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_4")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_5")]]
          ),
          custom.model.names = rep(paste0("(", 1:5, ")"), 2),
          label = paste0("table:opt_", h, n, "_", a),
          caption = paste0(
           "Probability of returning to ", h, " containing high school. ",
           "First-stage partial F-statistic for HS shock: ", round(hs_f_stat, 2),
           ", R-squared: ", round(hs_r_squared, 2),
          "; First-stage partial F-statistic for college shock: ", round(col_f_stat, 2),
           ", R-squared: ", round(col_r_squared, 2)),
          center = FALSE,
          digits = 3,
          custom.gof.rows = controls,
          custom.coef.map = nestedlist,
          file = paste0(directory, "/Outputs/Tables/opt_", h, n, "_", a, "_2019-24.tex"),
          append = TRUE
        )
      }
    }
  }

```


##    Single-Year Regressions

```{r}

models <- list()
years <- 2000:2021
# Prepare data to collect coefficients
coef_data <- data.frame()

for(yr in years)
{
  for(h in geos) {
    data <- if(h == "cbsa") regression_cbsa else regression_state
    data[col_end == yr]
    for(a in avgs) {
      # Retrieve relevant statistics for the current average type
      #hs_f_stat <- hs_stats[[as.character(a)]]$f_stat
      #hs_r_squared <- hs_stats[[as.character(a)]]$r_squared
      #col_f_stat <- col_stats[[as.character(a)]]$f_stat
      #col_r_squared <- col_stats[[as.character(a)]]$r_squared
      for(n in norm)
      {
        for(s in stage) 
        {
          hs_var <- paste0("hs", s, n, "_", a)
          col_var <- paste0("col", s, n, "_", a)
          current <- paste0("same_", h, "_hs ~ ", paste(hs_var, col_var, sep=" + "))
          
          formula <- c(
            current,
            paste0(current, " + inst_group + in_state + (inst_group * in_state)"),
            paste0(current, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3"),
            paste0(current, " + inst_group + in_state + (inst_group * in_state) + non_traditional + transfer + col_major + soc_3 + hs_state")
          )
          
          for (f in 1:length(formula)) 
          {
            form <- formula[f]
            model <- lm(form, data = data)
            models[[paste0(h, s, n, "_avg_", a, "_", f)]] <- model
            model_key <- paste0(h, stage[1], norm[1], "_avg_", a, "_", f)
            coef_data <- coef_data %>%
              bind_rows(
                data.frame(
                  year = yr,
                  hs_var = hs_var,
                  col_var = col_var,
                  geo = h,
                  avg = a,
                  model = f,
                  hs_coef = coef(model)[hs_var],
                  hs_conf_low = confint(model)[hs_var, 1],
                  hs_conf_high = confint(model)[hs_var, 2],
                  col_coef = coef(model)[col_var],
                  col_conf_low = confint(model)[col_var, 1],
                  col_conf_high = confint(model)[col_var, 2]
                )
              )
          }
          
          # Define control inclusion for each model
          controls <- list(
            "Undergraduate Major FE" = c("No", "No", "Yes","Yes", "No", "No", "Yes","Yes"),
            "Transfer and Non-Traditional FE" = c("No", "No", "Yes","Yes", "No", "No", "Yes","Yes"),
            "Occupational Group FE" = c("No", "No", "Yes","Yes", "No", "No", "Yes","Yes"),
            "High School State FE" = c("No", "No", "No", "Yes", "No", "No", "No",  "Yes")
          )
        }
        texreg(
          list(
            models[[paste0(h, stage[1], n, "_avg_", a, "_1")]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_2")]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_3")]],
            models[[paste0(h, stage[1], n, "_avg_", a, "_4")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_1")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_2")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_3")]],
            models[[paste0(h, stage[2], n, "_avg_", a, "_4")]]
          ),
          custom.model.names = rep(paste0("(", 1:4, ")"), 2),
          label = paste0("table:opt_", h, n, "_", a),
          #caption = paste0(
           #"Probability of returning to ", h, " containing high school. ",
           #"First-stage partial F-statistic for HS shock: ", round(hs_f_stat, 2),
           #", R-squared: ", round(hs_r_squared, 2),
          #"; First-stage partial F-statistic for college shock: ", round(col_f_stat, 2),
          # ", R-squared: ", round(col_r_squared, 2)),
          center = FALSE,
          digits = 3,
          custom.gof.rows = controls,
          custom.coef.map = nestedlist,
          file = paste0(directory, "/Outputs/Tables/opt_", h, n, "_", a,"_",yr,".tex"),
          append = TRUE
        )
      }
    }
  }
}

write.csv(coef_data,file.path(directory,"Data/06","coef_data.csv"))
  

```